buildscript {
    repositories {
        maven { url = "https://repo.spongepowered.org/maven" }
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

apply plugin: 'org.spongepowered.mixin'


version = '1.0'
group = 'com.yourname.modid'
base.archivesName = "modid"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.2'
    copyIdeResources = true

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file("run")
            source sourceSets.main

            args "--username", "Dev"
            if (System.getenv("MCREATOR_JVM_OPTIONS")) {
                jvmArgs System.getenv("MCREATOR_JVM_OPTIONS").split("\\s+").findAll { it.trim() }
            }

            mods {
                "modid" { source sourceSets.main }
            }

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.debug.export', 'true'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', 'build/createMcpToSrg/output.tsrg'
        }

        server {
            workingDirectory project.file("run")
            source sourceSets.main

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = "https://maven.terraformersmc.com/" } // Pour mixinextras
    maven { url = "https://repo.spongepowered.org/maven" }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}


mixin {
    add sourceSets.main, "skyzeradventure.refmap.json"
    config "skyzeradventure.mixins.json"
}

dependencies {
    // Forge (obligatoire)
    minecraft "net.minecraftforge:forge:1.18.2-40.2.17"

    // MixinExtras
    implementation "io.github.llamalad7:mixinextras-common:0.4.1"
    runtimeOnly "io.github.llamalad7:mixinextras-forge:0.4.1"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest.attributes([
        "MixinConfigs": "skyzeradventure.mixins.json"
    ])
    finalizedBy 'reobfJar'
}

apply from: 'mcreator.gradle'
