plugins {
    id 'eclipse'
    id 'net.neoforged.moddev.legacyforge' version '2.0.107'
}

version = '1.0'
base.archivesName = "modid"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = "1.18.2-40.3.11"

    runs {
        client {
            client()

            // Arguments "jeu" (équivalent de --username, etc.)
            programArguments.addAll([
                '--username','Dev',
                '--uuid','11111111-1111-1111-1111-111111111111',
                '--accessToken','0',
                '--userType','mojang'
            ])

            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.each { arg ->
                    jvmArgument(arg)
                }
            }

        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        mcreator {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

mixin {
    if (file("src/main/resources/skyzeradventure.mixins.json").exists()) {
        add sourceSets.main, "skyzeradventure.refmap.json"
        config "skyzeradventure.mixins.json"
    }
}

dependencies {
    implementation(jarJar("io.github.llamalad7:mixinextras-neoforge:0.5.0"))
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    if (file("src/main/resources/skyzeradventure.mixins.json").exists()) {
        manifest.attributes([
                "MixinConfigs": "skyzeradventure.mixins.json"
        ])
    }
}

apply from: 'mcreator.gradle'